config/routes.rb
Rails.application.routes.draw do
  root 'artists#index'

  resources :artists do #/artists
    resources :albums do #/albums/1/songs/1
      resources :songs #/artists/1/albums/1/songs/1
    end
  end

  resources :songs #songs routes

  resources :albums do #nested albums and songs 
    resources :songs #/albums/1/songs/1
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
 has_many :songs
 belongs_to :artist
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :albums
    has_many :songs, through: :albums
end

app/models/song.rb
class Song < ApplicationRecord
 belongs_to :album
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all
  end

  def new
    @album = Album.new
    @artist = Artist.find(params[:artist_id])
  end
 def create
    album = Album.create(albums_params)
    redirect_to artists_path
  end
  def edit
  end

  def show
    @album = Album.find(params[:id])
  end

  private 
  def albums_params
        params.require(:album).permit(:name, :cover, :year, :artist_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def new
  end

  def edit
  end

  def show
    @artist = Artist.find(params[:id])
        @album = Album.new

  end

  private
  def artist_params
    params.require(:artist).permit(:name)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.all
  end

  def new
  end

  def edit
  end

  def show
    @song = Song.find(params[:id])
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/albums/_form.html.erb
 <%= form_for @album do |f| %>
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name, required: true %>
    </div>
     <div class="field">
      <%= f.label :cover %>
      <%= f.url_field :cover %>
    </div>
     <div class="field">
      <%= f.label :year %>
      <%= f.number_field :year%>
    </div>
      <%= f.hidden_field :artist_id, :value => @artist.id %>
    <%= f.submit "Add" %>
  <% end %>

app/views/albums/edit.html.erb
<h1>Albums#edit</h1>
<p>Find me in app/views/albums/edit.html.erb</p>

app/views/albums/index.html.erb
<div class="container mt-5">
  <div class="card-columns">
    <% @albums.each do |album| %>
      <div class="card">
        <%# <img class="card-img-top" src="..." alt="Card image cap"> %>
        <%= image_tag album.cover, class: "card-img-top" %>
        <div class="card-body">
          <h5 class="card-title"><%= link_to album.name, album_path(album) %></h5>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/albums/new.html.erb
<h1>Albums#new</h1>
<p>Find me in app/views/albums/new.html.erb</p>
<%= render partial: 'form' %>

app/views/albums/show.html.erb
<div class="container mt-5">
    <div class="row">
        <div class="col-2">
        <%= image_tag @album.cover, :style => "width:150px; height:150px"  %>
        </div>
         <div class="col-9">
            Album Name : <h3><%= @album.name %> </h3>
            Album Artist : 
            <h4><%= link_to @album.artist.name, artist_path(@album.artist.id) %> </h4>
        </div>
    </div>

</br>
<table class="table">
<% if  @album.songs.size < 1 %>
  <div class="alert alert-warning">
    No Songs listed
  </div>

<% else %>
<% @album.songs.each do |song| %>
    <tr>
        <td><%= song.name %></td>
        <td>
            <audio controls
                src="<%= song.url %>">
                    Your browser does not support the
                    <code>audio</code> element.
            </audio>
        </td>
    </tr>
 
 
<% end %>
<% end %>
</table>
</div>

app/views/artists/edit.html.erb
<h1>Artists#edit</h1>
<p>Find me in app/views/artists/edit.html.erb</p>

app/views/artists/index.html.erb
<h2 class="text-center">Favourite Artist</h2>

<div class="container">
 <div class="list-group">
  <% @artists.each do |artist| %>
     <%= link_to artist.name, artist_path(artist), class: "list-group-item list-group-item-action" %>
  <% end %>
 </div>
</div>

app/views/artists/new.html.erb
<h1>Artists#new</h1>
<p>Find me in app/views/artists/new.html.erb</p>

app/views/artists/show.html.erb
<div class="container mt-4">

 <h2> Artist : <%= link_to @artist.name, artist_path(@artist) %> </h2>
 
  <table class="table">
   <thead>
      <th> Cover Image</th>
      <th> Year</th>
      <th> Name</th>
    </thead>
   <% @artist.albums.each do |album|  %>
   <tr>
     <td> <%= image_tag album.cover, style: "width:100px; height:100px" %></td>
     <td> <%= album.year %></td>
     <td><%= link_to album.name, artist_album_path(@artist,album) %></td>
   </tr>  
   <% end %>
  </table>
</div>

<%= link_to 'Add Album', "/artists/#{@artist.id}/albums/new" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SongsPlayer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">

        <!-- Links -->
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="/artists">Artists</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/albums">Albums</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/songs">Songs</a>
          </li>
        </ul>

      </nav>
    <%= yield %>
  </body>
</html>

app/views/songs/edit.html.erb
<h1>Songs#edit</h1>
<p>Find me in app/views/songs/edit.html.erb</p>

app/views/songs/index.html.erb
<div class="container mt-5">
  <table class="table">
    <thead>
      <th> Name</th>
      <th> Player</th>
      <th> Album Cover</th>
      <th> Action</th>
    </thead>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.name %></td>
        <td><audio controls
                src="<%= song.url %>">
                    Your browser does not support the
                    <code>audio</code> element.
            </audio></td>
        <td> <%= image_tag song.album.cover, style: "width:100px;height:100px;" %> </td>
        <td> <%= link_to "View Album", album_path(song.album) %> </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/songs/new.html.erb
<h1>Songs#new</h1>
<p>Find me in app/views/songs/new.html.erb</p>

app/views/songs/show.html.erb
<h1>Songs#show</h1>
<p>Find me in app/views/songs/show.html.erb</p>